POST http://localhost:3000/api/postNote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2U0MThmYzcxNWYxNDY4NTliODBlYmYiLCJ1c2VybmFtZSI6IkFybmF1IiwiaWF0IjoxNjc1OTAzMTE4fQ.bqBvdOkfIV4u04BTS_hbukW9kS1dlFnAUFdn05f-oGU

{
    "title": "Tercer Nota",
    "content": "AMB USUARI encriptat i jwt"
    
}